#!/bin/bash

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


#install Brave + Chrome browsers
brew cask install brave=browser
brew cask install google-chrome

# Install Zoom + does not work needs to be de-installed and installed manually
brew cask install zoom
brew cask remove zoom

# Install docker
brew cask install docker

# install unix utilities
brew install curl
brew install wget
brew install python3
brew install git
brew install wireguard-tools
brew cask install telegram

# Needs to have the unknown software check set to allow.
brew cask install virtualbox

# create bootable install usb 
sudo /Applications/Install\ macOS\ Catalina.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume

